- name: Generate an AWX API token from AWX
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Generate an AWX API token
      ansible.builtin.uri:
        url: "http://192.168.49.2:32275/api/v2/tokens/"
        method: POST
        user: "admin"
        password: "rWifnIyyVKA2WhEYjkDuTbOCVYca7aIG"
        force_basic_auth: yes
        status_code: 201
        return_content: yes
      register: token_response

    - name: Show the token
      debug:
        msg: "Token: {{ token_response.json.token }}"
